name: spotify_clone
description: "A new Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  flutter_bloc: ^8.1.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  get_it: ^8.0.0
  dartz: ^0.10.1

dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
    - assets/images/logo.webp
    - assets/images/eric.jpg
    - assets/images/Dua.jpeg
    - assets/images/gline.png
    - assets/images/bili.png

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 300